project:
  type: book

book:
  title: "**Toxic cocktails in soils** - Evidence for synergistic effects of a pesticide mixture on earthworm life-history traits"
  subtitle: "Git repository"
  author:
    - name: "Lisa Gollot"
      orcid: "https://orcid.org/0009-0004-5074-4275"
      affiliations:
        - name: "Université Paris-Saclay, INRAE, AgroParisTech, UMR 1402 ECOSYS"
          department: "Sol&Tox"
        - name: "Experimental Toxicology and Modeling Unit, INERIS, Verneuil en Halatte 65550, France"
    - name: "Cleo Bodin"
      orcid: "https://orcid.org/0000-0003-3470-157X"
      affiliations:
        - name: "Experimental Toxicology and Modeling Unit, INERIS, Verneuil en Halatte 65550, France"
    - name: "Laura Frattaroli"
      orcid: ""
      affiliations:
        - name: "Université Paris-Saclay, INRAE, AgroParisTech, UMR EcoSys, 91120 Palaiseau, France"
    - name: "Rémy Beaudouin"
      orcid: "https://orcid.org/0000-0002-2855-1571"
      affiliations:
        - name: "Experimental Toxicology and Modeling Unit, INERIS, Verneuil en Halatte 65550, France ; Institut national de l'environnement industriel et des risques, Université de Reims Champagne-Ardenne, Université Le Havre Normandie, Normandie Univ, UMR-I 02 SEBIO, 60550 Verneuil-en-Halatte, France"
    - name: "Raphaël Royauté"
      orcid: "https://orcid.org/0000-0002-5837-633X"
      affiliations:
        - name: "Université Paris-Saclay, INRAE, AgroParisTech, UMR EcoSys, 91120 Palaiseau, France"
    - name: "Juliette Faburé"
      orcid: "https://orcid.org/0000-0002-8055-3224"
      affiliations:
        - name: "Université Paris-Saclay, INRAE, AgroParisTech, UMR EcoSys, 91120 Palaiseau, France"
        
  date: "6/25/2024"
  chapters:
    - index.qmd
    - quarto/A_Earthworm_culture.qmd
    - part: quarto/B_TD_Single/B_TD_EPX_IMD_single.qmd
      chapters: 
        - quarto/B_TD_Single/BA_Preliminary_tests.qmd
        - quarto/B_TD_Single/BB_Effect_single.qmd
    - part: quarto/C_TD_Mix/C_TD_EPX_IMD_mix.qmd
      chapters:
        - quarto/C_TD_Mix/CA_How_to_study_mixture.qmd
        - quarto/C_TD_Mix/CB_Effect_cocoons_mix_design.qmd
        - quarto/C_TD_Mix/CC_Effect_cocoons_mix_power.qmd
        - quarto/C_TD_Mix/CD_Effect_cocoons_mix_analysis_Autumn2024.qmd
        - quarto/C_TD_Mix/CE_Comparison_Single_Mix.qmd
        - quarto/C_TD_Mix/CF_Effect_cocoons_mix_analysis_Spring2025.qmd
        - quarto/C_TD_Mix/CG_Effect_cocoons_mix_analysis_otherEndpoints.qmd
    - quarto/references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/LisaGllt/Ew-Mix-TD

bibliography: references/references.bib # ne pas exporter toute la bibliothèse juste la collection PhD
csl: references/apa.csl
execute:
  cache: true
  freeze: auto
execute-dir: project
format:
  html:
    code-fold: true
    code-tools: true
    code-block-bg: true
    highlight-style: appearance/lightnord.theme
    code-block-border-left: "#E5E9F0"
    code-overflow: wrap
    code-annotations: select
    theme:
      - cosmo
      - appearance/html_css.scss

editor: 
    markdown:
      canonical: true

